name: build maven

on: 
    workflow_dispatch:
    push:
        branches: [ "main" ]
jobs:
    checkoutapp: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Setup Java JDK
          uses: actions/setup-java@v4

        - name: building app
          run: mvn clean package
          
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.3
          with:
            name: hello-0.0.1-SNAPSHOT.jar
            path: ./target
            retention-days: 1
            
    pushtogithub: 
        needs: checkoutapp
        uses: ./.github/workflows/triggered.yml
        
