name: hello-spring

on: 
    workflow_dispatch:
    push:
        branches: [ "main" ]
jobs:
    checkoutapp: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: installing the maven
          uses: yuzhiyongcn/setup-maven@v1.0.0
          with:
            maven-version: 3.8.2
            
        - name: building app
          run: mvn clean package
          
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.3
          with:
            name: hello-0.0.1-SNAPSHOT.jar
            path: ./target
            retention-days: 1
            
    pushtogithub: 
        needs: checkoutapp
        uses: ./.github/workflows/triggered.yml


    DockerLogin:
        runs-on: ubuntu-latest
        needs: ["pushtogithub"]
        steps:
            - name: Docker Login
              uses: docker/login-action@v3.0.0
              with:
                  username: ${{ secrets.Docker_Username }}
                  password: ${{ secrets.Docker_Password }}

    Docker_Build_And_Push:
        runs-on: ubuntu-latest
        needs: [ "DockerLogin" ]
        steps:
            - name: Build and push Docker images
              uses: docker/build-push-action@v5.0.0
              with:
                context: .
                push: true
                tags: hemanth12reddy/git-hub-actions:latest
                github-token: ${{ _GITHUB_TOKEN }}
          
        

          
